### ISSUE TITLE
Cannot build in XCode Version 7.3.1 (7D1014)

### ISSUE THREAD

**Issue by Godlike-Productions** [RomanKubiak/ctrlr#213]
I need to build a copy of ctrlr for OSX with the following Extra Linker Flags -Xlinker -headerpad -Xlinker 800

I've forked the repository and opened it in the latest version of Projucer.

I add in the flags, but when I try to build I get the following errors.  I don't know much about C++ or XCode, so any help would be appreciated.

```
juce_MathsFunctions.h:266:5: error: statement not allowed in constexpr function
    jassert (lowerLimit <= upperLimit); // if these are in the wrong order, results are unpredictable..
    ^
```

15 errors related to jlimit
```
juce_AudioDataConverters.h:107:82: error: no matching function for call to 'jlimit'
```

and finally

```
Source/Misc/luabind/luabind/config.hpp:27:10: fatal error: 'boost/config.hpp' file not found
#include <boost/config.hpp>
         ^
```

which I'm assuming is boost missing somewhere. I'm not sure what this is or how to go about fixing it.

I'm new to trying to build at this level. I have a ctrlr module ready to deploy but can't get copy protection done with the AU plugin due to the Extra Linker Flags.

Alternatively I'm happy to throw someone some dollars to do a build of Version = 5.3.198, Build date = Tue Mar 15 15:53:07 PDT 2016, Branch = Nightly, Juce = 4.0.2, libusb = 1.0.19, liblo = 0.28, with the Extra Linker Flags so I can do my copy protection.

**Comment by Godlike-Productions** [comment]
Actually I'm happy to throw some dollars if someone can do a build of the current OSX version with the extra linker flags.  I don't think exported instances from 5.3.198 will run under modern OSX versions. It will likely be quicker than for me to work out how to build it myself.

**Comment by Godlike-Productions** [comment]
I'm going to try to lease an M1 Mac for 6 months to get this sorted. At least then I'll have the latest version of XCode, and it should be enough for me to finalize development.
